[package]
name = "rust-db-test"
version = "0.1.0"
authors = ["Dmitrii Goriunov <goriunovd@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.14"
postgres = "0.15"
futures = "0.1"
tokio-threadpool = "0.1"
tokio = "0.1"